### ISSUE TITLE
Visual Issue

### ISSUE THREAD

**Issue by SchnitzelJager045** [Direwolf20-MC/BuildingGadgets2#10]
The world dissappear when having destruction gadget in hand when using a shader in 1.20.1 
![2023-08-21_19 59 20](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/142832392/19f453f2-9eeb-4a4d-9e6d-9b0e838532e0)
![2023-08-21_19 59 26](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/142832392/8e246f01-8bb4-4036-8f20-1ce9fdfb52f4)

**Comment by Direwolf20-MC** [comment]
I've added a possible fix, but I don't usually use shaders so can't be sure :).  When the next version comes out please test for me, and open a new issue if not.
