### ISSUE TITLE
Cut, Copy / Paste gadgets break Pipez extraction settings reverting to default state and voiding installed upgrades

### ISSUE THREAD

**Issue by yurikus** [Direwolf20-MC/BuildingGadgets2#102]
**Building Gadgets Version**
buildinggadgets2-1.0.7.jar
pipez-forge-1.20.1-1.2.6.jar

MC 1.20.1
Forge 47.2.32

**Describe the bug**
Cut & Copy / Paste gadgets break Pipez extraction settings reverting to default state and voiding installed upgrades

**To Reproduce**
Build a couple of chests, connect them with item pipe, shift-r-click on one end, changing the pipe into extract mode from this inventory, add an ultimate upgrade. Using Cut/Paste Gadget, cut and paste then contraption. Extraction side of the pipe reverts to default mode, voiding ultimate upgrade.

**Expected behavior**
Pipez extraction end should remain in extraction mode with installed upgrade.

**Screenshots**

BEFORE:
![image](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/11010776/ab916ca9-2385-401c-8988-56c33d65d73a)

AFTER:
![image](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/11010776/f0526c04-3abc-4bb4-bdcf-4cab54cc90c8)

**Log Files** 
N/A

**Comment by Direwolf20-MC** [comment]
This is likely due to how Pipez works
