### ISSUE TITLE
All build gadgets bypass ftbchunk claims!

### ISSUE THREAD

**Issue by funnycubeguy** [Direwolf20-MC/BuildingGadgets2#103]
**Building Gadgets Version**
BuildingGadgets2-1.0.7

**Describe the bug**
All building gadgets bypass FTB chunks claims.

**To Reproduce**
Use any build gadget in a claimed chunk.

**Expected behavior**
Should not work in claimed chunks.

The ftbchunks dev's say the a building gadgets issue as it uses the wrong event to place or alter blocks. Please fix this it has been like this forever!

**Comment by Direwolf20-MC** [comment]
Resolved :) thanks!

**Comment by jmadarg** [comment]
@Direwolf20-MC is the fix only for 1.21? Any possibility for a backport to 1.20.1?
