### ISSUE TITLE
Building Gadgets slow load

### ISSUE THREAD

**Issue by DMOO5H** [Direwolf20-MC/BuildingGadgets2#107]
**Building Gadgets Version**
1.20.1

**Describe the bug**
So my game’s FPS is relatively high averaging 60-80 FPS, but my building gadgets effects upon using it, like let’s say when placing the blocks are really slow and I have no idea why

**To Reproduce**
This happens every time I use one of the building gadgets

**Expected behavior**
The gadgets should load fast as per usual

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by Direwolf20-MC** [comment]
Can you go into more detail about the slowness?

**Comment by Direwolf20-MC** [comment]
This should be fixed now
