### ISSUE TITLE
[Suggestion] Randomly Exchanged blocks

### ISSUE THREAD

**Issue by winsrp** [Direwolf20-MC/BuildingGadgets2#109]
**Building Gadgets Version**
Using latest version for 1.19.2

So have you seen a wall full of stone bricks, looks boring, but have you seen the same wall with randomly placed, stone bricks, cracked stone bricks, mossy stone bricks and stone, looks awesome!

So it would be great if the exchanger had a feature to randomly replace blocks in an area, every time you click it will replace a different pattern, so you can select lets say cracked stone bricks and randomly replace just a few, then select mossy bricks and randomly replace a different pattern on the same wall... and after a few materials and clicks it will look great!

Thanks!
-Winsrp

**Comment by Direwolf20-MC** [comment]
Its a good idea, i'll get to it some day :)
