### ISSUE TITLE
Cut/Paste Tool Sugestion

### ISSUE THREAD

**Issue by ChosenArchitect** [Direwolf20-MC/BuildingGadgets2#11]
After testing the tool it might need a max amount of blocks (configurable or at least a warning) that it can do that one time. It can move a huge amount of blocks and it also drops all those replaced items into the world causing a lot of FPS lag. Also, I can see people using it as a Mining tool to clear entire chunks with AIR and gather the items with it. I don't know if some sort of items package (like how the old-school OP picks would drop the items inside of an orb) would solve this issue but this tool is crazy powerful and I love it!

**Comment by Direwolf20-MC** [comment]
You're not wrong :) Theres currently a limit of 100,000 blocks. I have a 'todo' for myself to make that configurable.  The main intention was as a builder, but when i added the ability to exchange (which was mostly added for the benefit of the cut/paste) it made things a bit OP now.  Maybe I should remove that exchange option.  Its *cool* but its use as a large scale miner is unsettling to me.

**Comment by Direwolf20-MC** [comment]
Actually i thought of a compromise - the exchange acts as a void - it doesn't give you back the blocks it overwrote :).

**Comment by ChosenArchitect** [comment]
I approve this message :D

**Comment by Direwolf20-MC** [comment]
Resolved - copy (and cut) tools now void any drops from the blocks they replace. Use at your own risk going forwards!

Added a tooltip to the gadgets when this mode is enabled as well.
