### ISSUE TITLE
Attempting to paste CC:Tweaked Network Cable/Modem Crashes Java

### ISSUE THREAD

**Issue by Did-Nikole** [Direwolf20-MC/BuildingGadgets2#110]
**Building Gadgets Version**
BuildingGadgets V2-1.0.7

**Describe the bug**
Was attempting to paste a copy of a generator setup that included CC:Tweaked network cables

**To Reproduce**
Copy an area that contains an attached CC:Tweaked network modem/cable
Then attempt to paste

**Expected behavior**
The network cable to be placed with the appropriate modem/cable pointing at the item it was attached to (not necessarily configured)

**Screenshots**
![Screenshot from 2024-07-14 18-31-24](https://github.com/user-attachments/assets/88b0c783-5e4f-4a6c-a22c-2f9c8c864af6)

**Log Files** 
[crash-2024-07-14_18.08.13-server.txt](https://github.com/user-attachments/files/16215843/crash-2024-07-14_18.08.13-server.txt)

**Comment by Direwolf20-MC** [comment]
I'm not sure if I'll be able to fix this - i'd say for now just don't copy those cables anymore :D

**Comment by Fr3shlama** [comment]
is there a blacklist we can set up so it doesnt even copy the blocks
