### ISSUE TITLE
Templates crashing game

### ISSUE THREAD

**Issue by Uncraftbar** [Direwolf20-MC/BuildingGadgets2#112]
**Building Gadgets Version**
buildinggadgets2-1.3.3.jar Neoforge 1.21

**Describe the bug**
Trying to Sneak click Templates on the ground crashes the game.
Clicking on material list in the template manager also crashes the game, even with no template inside

This occured to while playing atm10 and i tried it with only the mod installed and nothing else in neoforge version 21.0.133 and 21.0.117

**To Reproduce**
Get a template, sneak click ground

**Expected behavior**
The making of a new template (havent used them before, not quite sure what would happen)

**Log Files** 
https://mclo.gs/hKoED9m

**Comment by Direwolf20-MC** [comment]
Thanks for the report - should be fixed :)
