### ISSUE TITLE
Crash when trying to acess Materials List when it includes items from missing mod

### ISSUE THREAD

**Issue by Jmpp2909** [Direwolf20-MC/BuildingGadgets2#113]
**Building Gadgets Version**
buildinggadgets2-1.3.3.jar

**Describe the bug**
When using the Copy-Paste gadget, clicking Materials List on a schematic where the mod/item doesnt exist will crash the game
Pack where schematic was made had Flux Networks, which i used Flux Points on the Schematic
Used the schematic on a different pack where Flux Networks isnt present - acessing materials list will crash the game, be it on the table or on the gadget itself

**To Reproduce**
Make a schematic using blocks from a mod, try to use it on a pack without those blocks existing, try to acess Materials List

**Expected behavior**
Not crash 🤣 
Should have a check for invalid blocks/items

**Screenshots**
![image](https://github.com/user-attachments/assets/293953d4-cfd5-4e86-9ac2-a00ee3954587)
doesnt help much, but thats part of the original schematic
will just crash if i try to acess on a pack without flux networks

**Log Files** 
 https://mclo.gs/kaDzRI2

**Comment by Direwolf20-MC** [comment]
I think i've got it fixed ;) we'll see!
