### ISSUE TITLE
Trying to paste an Ender Tank crashes the game

### ISSUE THREAD

**Issue by shiftthedev** [Direwolf20-MC/BuildingGadgets2#114]
**Building Gadgets Version**
1.0.7

**Describe the bug**
If an Ender Tank is inside the copied area, when changing to paste the game crashes and you cant enter that world again without removing the Copy/Paste Gadget from the inventory.

**To Reproduce**
- Get a Copy/Paste Gadget
- Copy an area with an Ender Tank in it
- Change gadget to paste

**Expected behavior**
Not crashing.

**Log Files** 
[Crash-Report](https://mclo.gs/BPyZxf6)

Notes:
This happen in Project Architect 2.
If you need us to test anything else just ask.

**Comment by Direwolf20-MC** [comment]
Can you let me know if this happens in 1.21 still? :) It should be solved now.

**Comment by 5ully** [comment]
Can you fix this for the mod version on minecraft 1.20.2 too?
