### ISSUE TITLE
OpenGL Renderer Crashes on holding Building Gadget (1.20.1)

### ISSUE THREAD

**Issue by lunabups** [Direwolf20-MC/BuildingGadgets2#115]
**Building Gadgets Version**
1.0.7 for 1.20.1

**Describe the bug**
Whenever selecting the building gadget, OpenGL Renderer crashes, leaving minecraft a blank black screen until I close it manually

**To Reproduce**
Have a fully charged building gadget, select a block, then attempt to use it like normal

**Expected behavior**
Normal usage, ie, no crashes

**Log Files** 
[2024-08-01-2.log.gz](https://github.com/user-attachments/files/16458343/2024-08-01-2.log.gz)

Pack is Worldly Galaxies IV with BSL shaders enabled, to easily setup the exact scenario I was in. This Mod has worked fine for a few weeks, and has suddenly just decided to cause problems.

**Comment by lunabups** [comment]
Can confirm with some extra testing that it seems to be some sort of rendering error with this mod and embeddium/oculus, or just with BSL itself, turning off the shaders fixes the issue. Unfortunately not a proper solution as forgetting to turn off the shaders results in a crash lol.

**Comment by Direwolf20-MC** [comment]
Unfortunately I don't think theres much I can do here :(
