### ISSUE TITLE
[Feature] Copy/Paste ignore air blocks toggle

### ISSUE THREAD

**Issue by Barerock** [Direwolf20-MC/BuildingGadgets2#116]
It'd be nice to be able to paste irregular shaped selections without being forced to void blocks that aren't actually occupied in the paste. Example, a circle has air gaps around the corners and those air blocks are treated equally to blocks. It would be extremely nice to ignore air optionally, since sometimes it's necessary.

**Comment by Direwolf20-MC** [comment]
I think there’s a setting when pasting to not overwrite blocks. Wouldn’t that work?

**Comment by Barerock** [comment]
Well my issue rn is that I'm trying to make street tiles, but I need it to overwrite in order to replace the ground level; however, the square selection prevents circular tiles from being pasted with less effort than just doing them by hand by voiding the air blocks as well.

**Comment by Direwolf20-MC** [comment]
Unfortunately because of the way the data is stored I need to capture the air blocks. Believe it or not it’s much more efficient that way

**Comment by Barerock** [comment]
Oh I believe you that it's more efficient. That's unfortunate that there's a limitation for this, it really is a helpful alternative to WorldEdit, and I'm missing the -a context command from that.

**Comment by Direwolf20-MC** [comment]
I’ll see if I can find a way :)
