### ISSUE TITLE
Feature Request: Lessen valid block requirements for creative players

### ISSUE THREAD

**Issue by curin** [Direwolf20-MC/BuildingGadgets2#117]
**Building Gadgets Version**
1.3.5

**Describe the feature**
Allow Players in creative mode to manipulate any safe block like bedrock or other blocks which only Creative players can interact with.

**Expected behavior**
A Player should be able to select, exchange, destroy, cut, or copy Bedrock.

**Comment by curin** [comment]
After thinking about this a little more it would probably be good for this to be a toggle as it is helpful, especially when using the destruction gadget to clear the non-indestructible blocks as I use the indestructible blocks as the bounds for the space mostly

**Comment by Direwolf20-MC** [comment]
At this time I don't want to make this change, sorry!
