### ISSUE TITLE
Claim Bypass

### ISSUE THREAD

**Issue by cookta2012** [Direwolf20-MC/BuildingGadgets2#118]
**Building Gadgets Version**
1.0.7

**Describe the bug**
Does not respect protected claims

**To Reproduce**
Use ftb to claim

**Expected behavior**
Don't allow block exchanging or destruction in protected claim

**Comment by Direwolf20-MC** [comment]
This is resolved in newer versions.

**Comment by cookta2012** [comment]
The newer version is not avail for 1.20.1 can you please port it?
