### ISSUE TITLE
[Suggestion] Add a Tag for Gadgets

### ISSUE THREAD

**Issue by TheBedrockMaster** [Direwolf20-MC/BuildingGadgets2#119]
Add a tag to give to all the gadgets. For example add a buildinggadgets2:gadgets tag to give to all the gadgets.

**Comment by Direwolf20-MC** [comment]
For what purpose?

**Comment by TheBedrockMaster** [comment]
For general grouping, however my specific case would be to make it easier to make a quest to obtain any of them.
