### ISSUE TITLE
Exchanging Gadget for slabs on bottom half not working

### ISSUE THREAD

**Issue by rannday** [Direwolf20-MC/BuildingGadgets2#121]
**Building Gadgets Version**
1.0.7

**Describe the bug**
Trying to replace slabs placed on the bottom half of a block only replaces the top half of the slab. Bottom half still removed, but new/replaced slabs are on the top half.

**To Reproduce**
ATM9 To the Sky - 1.1.1 - Replace slabs on the bottom portion.

**Expected behavior**
Replace the slabs on the bottom half, not the top.

**Screenshots**
![2024-08-12_11 31 26](https://github.com/user-attachments/assets/cd81b908-0646-443a-b04c-a43014e44853)
![2024-08-12_11 32 24](https://github.com/user-attachments/assets/ff04183b-48da-4040-974d-06867aeb7fc6)

**Comment by Direwolf20-MC** [comment]
Slabs are super janky, so i think this has to be how it is for now unforutunately.
