### ISSUE TITLE
Suggestion: Save nbt data for framed blocks.

### ISSUE THREAD

**Issue by VoidTest** [Direwolf20-MC/BuildingGadgets2#122]
Copy pasting framed blocks is nice but the texture does not paste ever since the nbt data isint saved by the gadget.
I would love some kind of integration with the mod for them to work together and allow for a better and easier building experience with both.

**Comment by Gloval** [comment]
Agreed.  This is one of the "lost features" from Building Gadgets 1 I would like to see make a comeback.

**Comment by Direwolf20-MC** [comment]
I definitely need to add something like this at some point!
