### ISSUE TITLE
Not Compatible with custom blocks made with Little Tiles mod. No crashing. It just doesn't place the little tiles blocks

### ISSUE THREAD

**Issue by YeetboiPro** [Direwolf20-MC/BuildingGadgets2#123]
**Building Gadgets Version**
Newest Version as of 8/23/24

**Describe the bug**
When I try to copy and paste custom blocks made with little tiles, it doesn't place the blocks.

**To Reproduce**
Copy custom little tiles blocks with some default blocks for good measure

**Expected behavior**
Will not place the blocks custom made with little tiles

**Screenshots**
The First Screenshot is what it's supposed to look like and the second one is what happens when I try to copy and paste it somewhere else.

![2024-08-23_16 59 51](https://github.com/user-attachments/assets/6bef450d-6ae6-4923-84cd-6d0ad4ab2724)

![2024-08-23_16 56 26](https://github.com/user-attachments/assets/95502e1f-4ff1-4498-9b28-eadb1481b74d)

**Comment by Direwolf20-MC** [comment]
The data is likely stored in NBT and I have no method for managing that at this time, sorry!
