### ISSUE TITLE
Show anchor in world when set

### ISSUE THREAD

**Issue by jerry1333** [Direwolf20-MC/BuildingGadgets2#124]
**Building Gadgets Version**
Any

**Describe the bug**
This is feature request - show anchor in world (like highlight block that anchor is set to)  - right now you have to set it again and again and if you forgot where it was set it's getting annoying :)

**To Reproduce**
N/A

**Expected behavior**
show anchor in world (like highlight block that anchor is set to)

**Screenshots**
Simple stuff like that should work totally fine:
![image](https://github.com/user-attachments/assets/e93b12b5-2999-409c-b7ab-2f45b6700a14)

**Log Files** 
Not this time...

**Comment by Gloval** [comment]
The Best Practices answer for this is put down a block and anchor to it so you know where to anchor to again if needed.  As a feature it woudl be interesting though.

**Comment by Direwolf20-MC** [comment]
I liked this idea and since I had something very similar in JustDireThings already, it was easy to copy over :)
