### ISSUE TITLE
[Suggestion] Add built-in template functionality in copy/paste gadget

### ISSUE THREAD

**Issue by Kegulf** [Direwolf20-MC/BuildingGadgets2#125]
Firstly, I mostly watch your YouTube series, I don't play much myself these days, but I had an idea for the copy/paste gadget.

Instead of a template manager block, why not add a built in template manager in the gadget itself that lets you store, save, load, search (etc) your templates?

That way you don't need to store templates outside of the gadget, and you'd be able to select a different template on the go.

Eventually make a portable manager or a tie-in to storage to access templates.

The template manager feels like a improvable experience with your improved programming skills :grin:

**Comment by Gloval** [comment]
One of the main functions of the Building Gadget mod is it's sharing feature/ability.  Taking the schematcis as a text file that can be shared with others.  As a text the "user" does not need to know about Windows directory structures or anything of the like to get a build.  Create uses a Template Table in game that links to a directory in the Minecraft instance "schematics"  and I have had to spend far longer than you would think is needed now a days to explain where that directory was and hot to download and copy a file to it for availability in game.

**Comment by Direwolf20-MC** [comment]
I kind of like how it works now :) i don't see a big need to remove the block
