### ISSUE TITLE
Adjust placement windows blurred, not eligible

### ISSUE THREAD

**Issue by Nidaelie** [Direwolf20-MC/BuildingGadgets2#127]
**Building Gadgets Version**
1.3.7

**Describe the bug**
When trying to use the adjust placement window it appears blurred and cant adjust nothing cause the coordinates and the buttns arent showing

**To Reproduce**
pasting and trying to relocate te build

Modpack: atm 10 

**Screenshots**
![2024-09-06_15 03 11](https://github.com/user-attachments/assets/3d546107-3ed9-4703-bb11-516d58fc7afc)

**Comment by Nidaelie** [comment]
PSA: There has been a bug for several updates now with GUI's not rendering properly due to some backend issues that are hard to pin down. If you have GUI's that are invisible or not showing properly go to your accessibility settings and change this setting to off. It's a temporary fix for now and may not be required in future updates

**Comment by jerry1333** [comment]
Just to be clear setting you should look for is "Menu Background Blur", set it to off.
![image](https://github.com/user-attachments/assets/747acaa1-63fd-41d9-893d-7a07a54270e7)

**Comment by Direwolf20-MC** [comment]
This is now fixed :)
