### ISSUE TITLE
Crash while attempting to preview building materials

### ISSUE THREAD

**Issue by MuteTiefling** [Direwolf20-MC/BuildingGadgets2#128]
**Building Gadgets Version**
buildinggadgets2-1.3.7

**Describe the bug**
Crash when viewing material list of copy

**To Reproduce**
1. Build a Modern Industrialization Boiler/turbine setup. Probably doesn't really matter what blocks tbh.
2. Copy it
3. Open the gadget and click the material list

**Expected behavior**
No Crash

**Log Files** 
[Crash logs are extremely important in helping me figure out how I DireDerped.](https://gist.github.com/MuteTiefling/22d196ef7a82cbb70d6ceab96309462a)

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by Gloval** [comment]
I assume this is a multiblock structure, seeing as you ar copying the build for reuse elsewhere.  If it was formed when you tried to copy it the Building Gadget can have issues telling what blocks it's made of.  I know Mekanism's reactors and such get awefully screwie if copiedor pasted in formed.  Best to leave a single block out of the structure then copy.  If sharing the schematci just note the missing block and what to fill it with.

**Comment by MuteTiefling** [comment]
Pretty sure it's a tank causing the crash, actually.

It's not part of the multiblock.

I removed it later and had no more issue.

**Comment by Direwolf20-MC** [comment]
I've pinged Tech about this, I *think* its on their side, but i'll confirm :)
