### ISSUE TITLE
Speed up option for gadgets

### ISSUE THREAD

**Issue by Hadoukanen** [Direwolf20-MC/BuildingGadgets2#132]
The animations and such are a bit slow. Maybe add overclocker cards or something, so you can "Turn up the power" of the gadgets so they work faster.

**Comment by Direwolf20-MC** [comment]
The slowness of the building is partially there to look cool - but also plays an important role in keeping the server and framerate from getting laggy due to many changes in a short time.  I'll consider adding an option somehow, but part of the reason for the slowness is performance :)
