### ISSUE TITLE
[Suggestion] Adding a Measuring Tape

### ISSUE THREAD

**Issue by ixDarkLorD** [Direwolf20-MC/BuildingGadgets2#133]
It will be nice to see a measuring tape item being added to this mod.
I often come across measuring tape mods, but some of them are visually unreadable due to poor design.

So I would like to:
Have visuals, such as highlighting the selected area and showing dimensions on the screen for better readability. Other players near the highlighted area can also see it for cooperation reason.

**Comment by Direwolf20-MC** [comment]
Its a nice feature, but may be out of scope for this mod :). I'll consider it though!
