### ISSUE TITLE
Domun Ornamentum gets bad-touched by Building Gadgets

### ISSUE THREAD

**Issue by Poojawa** [Direwolf20-MC/BuildingGadgets2#14]
Heyo! Just letting you know that Domum's handling of block data doesn't play nice with this build tool. But I'm pretty sure this is also just a general thing on their end as well. It's really not enjoyed existing on the server pack we've cobbled together.

MC: 1.19.2
buildinggadgets-3.16.2-build.22+mc1.19.2.jar
domum_ornamentum-1.19-1.0.107-RELEASE-universal.jar

using:
radon-0.8.2.jar
rubidium-0.6.2b.jar

What happened: made valid shingles. Placed one normally in the world, then used building tool copy and then pasted in a test sample to see if it'd work. 

Shingles were placed in the correct orientation as hoped for, but were a JEI generic plain clay and oak wood 'null' block that instantly crashes the client when interacted with (And the entire server when desperate TNT measures were undertaken, shhh). Details tooltip showed the JEI icon cycle of all the various examples

![2023-08-24_19 15 08](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/6293118/9bf58e6a-e9db-4ef8-b591-80e16dd1fe7a)
![2023-08-24_19 15 25](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/6293118/d8357cea-33ca-4509-9c4f-bca115b611f5)

Like I said, I know this is definitely on their end more than anything, but it always pays to ensure folks are aware!

**Comment by Direwolf20-MC** [comment]
Thanks! It’s likely how they are storing the data for the difference between all these shingles - if it’s stored in nbt then that’s the problem. I have plans to support a way to let people pick what safe nbt tags can be copied but for now I’d say just don’t use these 😅

**Comment by MichaelHillcox** [comment]
Oh, I've just noticed, this issue is with Building Gadgets 1, not Building Gadgets. You'd want to make an issue on https://github.com/Direwolf20-mc/BuildingGadgets
