### ISSUE TITLE
[Feature Request] Add a water only mode to the desctruction gadget

### ISSUE THREAD

**Issue by Sintinium** [Direwolf20-MC/BuildingGadgets2#140]
Water has always been a pain to deal with when building ocean bases or underground if you run into a very common water cave. Currently you can clear the water but it also destroys other blocks too. It would be nice if there was an option to leave the blocks and only target water.

**Comment by Direwolf20-MC** [comment]
Part of the goal of the destruction gadget was to avoid allowing you to filter what it destroys (To avoid you removing all the stone, and leaving behind ores). For now I'm gonna pass on this request, sorry!
