### ISSUE TITLE
Copy Paste Gadget's settings menu becomes blurry and unusable.

### ISSUE THREAD

**Issue by Zulussuu** [Direwolf20-MC/BuildingGadgets2#141]
**Building Gadgets Version**
buildinggadgets2-1.3.7

**Describe the bug**
When I open the settings menu of the Copy Paste Gadget, the whole screen becomes blurry and none of the buttons can be used.

**To Reproduce**
I'm playing on ATM10 version 1.1.6. To perform the bug, just open the general settings menu of the copy paste gadget and then press the "settings menu" button with the pencil icon at the bottom right.

**Expected behavior**
I expect the screen not to blur and the settings to be able to be used properly.

**Screenshots**
just press this button
![image](https://github.com/user-attachments/assets/6cc034e7-d154-4ec1-ba53-6c3d4143c212)

and here it is
![image](https://github.com/user-attachments/assets/dbb635e5-9639-401c-9a3f-d158d79216b9)

**Comment by NoorHajDawood** [comment]
temporary solution, you can disable Menu Background Blur in the Accessibility Settings.
this solves this issue, and also the same in renaming waystones and such

**Comment by Direwolf20-MC** [comment]
This should be resolved in the next version, thanks!
