### ISSUE TITLE
Feature request: Resize UI size for Template Manager (something like AE2 terminal UI size editor)

### ISSUE THREAD

**Issue by NoorHajDawood** [Direwolf20-MC/BuildingGadgets2#142]
**Building Gadgets Version**
1.3.7

The UI size for the Template Manager is fixed, and not adjustable.
Would be nice to have it adjustable something like AE2 terminal or better. or maybe just fill the screen when the minecraft UI sizing is not x3

**Comment by Direwolf20-MC** [comment]
I'll consider this feature as a future 'nice to have'.
