### ISSUE TITLE
[1.19.2] Crash when items(s) viewed in JEI

### ISSUE THREAD

**Issue by Sandriell** [Direwolf20-MC/BuildingGadgets2#15]
When attempting to view the mod's items in JEI (searching "@bu" is as far as it gets) the game is instantly crashing.

MC: 1.19.2
Forge: 43.2.21
Java: 18.0.2.1 x64

Crash report: https://gist.github.com/Sandriell/4da8957e3567532eeddbed6c3c44b8c6

Looks like there has been a [Pull Request](https://github.com/Direwolf20-MC/BuildingGadgets/pull/738) to fix this on the other Building Gadgets repo (why are there 2?).

**Comment by Direwolf20-MC** [comment]
This mod only works on 1.20.1 of Minecraft and above. The fact that it let you load at all is a bug I’ll fix. Sorry. Use building gadgets 1 for your version :)

**Comment by Sandriell** [comment]
I am using the 1.19.2 version. This is the Github that is linked on the curseforge page and there is no link for the other github there- hence my confusion earlier.

**Comment by X-XLebyshek** [comment]
If that will help you, I had this issue and the mod causing it turned out to be Connectedness (port of Connectivity). When I disabled it, everything worked normally. So if you have this mod in your pack, this is probably it
