### ISSUE TITLE
anchor persist after a paste

### ISSUE THREAD

**Issue by Stonurd** [Direwolf20-MC/BuildingGadgets2#153]
I used cut past gadget and it keep the anchor location AFTER A PASTE.
 
I PASTED WHILE HOLDING IT, IT ERASED ALL MY STORAGE BECAUSE THE ANCHOR WAS KEPT AFTER A PREVIOUS PAST, I'M SURE, EVERYONE HAVE MADE THIS MISTAKE. AND OF COURSE WHEN IT HAPPEN TO ME EVERYTHING GOT OBLITERATED, IT ALL YOUR FAULT, YES, ALL OF YOU FOR ALL THIS TIME DIDNT PUTTED THE MOST BASIC SAFETY.

**Comment by Direwolf20-MC** [comment]
Overwrite blocks is off by default. 
That’s the basic security.

**Comment by Stonurd** [comment]
I have no right on these rul in a server.

**Comment by Stonurd** [comment]
Closed  ??? Already ??? arent you going to make the mod clear the anchor after a paste ? Dont you want prevent disaster happening again and again, thus making server provider more expensive to manage ?

**Comment by Stonurd** [comment]
Its erasing backpack from sophisticated storage
