### ISSUE TITLE
Cant exchange Dry Ice from Powah

### ISSUE THREAD

**Issue by 3less** [Direwolf20-MC/BuildingGadgets2#16]
Hello, 

you cant exchange any Powah Blocks with Exchanging Gadgets (World Generation), like Dry Ice Blocks or Uranitite Ore, u have to change them manually with a Pickaxe. Hopefully this will be fixed.

**Comment by Direwolf20-MC** [comment]
Dry Ice is a block entity (Like a chest) and therefore you just need to enable block entity mode on the exchanger to allow exchanging it ;). 

Took me a bit to figure that out heh.
