### ISSUE TITLE
[1.20.1] Crash with Building Gadget and Connected Glass

### ISSUE THREAD

**Issue by lays24mc** [Direwolf20-MC/BuildingGadgets2#18]
If you want to "copy" the glass panes (like clear glass panes) from Connected Glass with the "Building Gadget" to set them with the tool, the client crashes with a "Tessellating block model" error. Join and select the gadget again, the client crashes. After that, however, joining on the server is no longer possible.

Crashlog: https://pastebin.com/rtBft4rD

Mods:

Building Gadget 0.2.0
Connected Glass 1.17-forge-mc1.20
Forge 1.20.1-47.1.3

**Comment by Direwolf20-MC** [comment]
Thanks! I’ll test it out :)

**Comment by Direwolf20-MC** [comment]
Resolved in v0.2.1 - Its pushed to curseforge now.
https://github.com/Direwolf20-MC/BuildingGadgets2/commit/4df07db8d4171a188cf8e0253170013f3fd84def
