### ISSUE TITLE
Exchanging gadget dosen't work in the nether.

### ISSUE THREAD

**Issue by NJM1564** [Direwolf20-MC/BuildingGadgets2#21]
Playing all the mods 9 and Exchanging gadget doesn't work in the nether.
Building gadget is working fine though.
Destruction gadget's undo doesn't seem to work at all.

**Comment by Direwolf20-MC** [comment]
Exchanger not working in the Nether should be fixed in the next version. 

Destruction Gadget undo not working -- I can't replicate this. Can you provide more details on how you caused it?

**Comment by NJM1564** [comment]
Got destruction gadget issue fixed. Turned out the pack has a second entry in key configs for undo. Mouse over only listed it as "building tool". No look up in NEI/JEI (what ever it is called now a days). Pack recycles a lot of configs from the ATM8, so could be for something that only existed in that pack.

**Comment by Direwolf20-MC** [comment]
Cool thanks :)
