### ISSUE TITLE
Crash when trying to save template

### ISSUE THREAD

**Issue by cameronkh** [Direwolf20-MC/BuildingGadgets2#23]
[crash-2023-09-09_16.03.24-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/12566841/crash-2023-09-09_16.03.24-client.txt)

**Comment by Direwolf20-MC** [comment]
The cause of this crash is Rubidium - please remove it and see if you still crash.

**Comment by cameronkh** [comment]
Removing the mod fixed the crash. Thank you dire.

**Comment by Direwolf20-MC** [comment]
No problem! Lots of others are having the same issue so I added it to the new issue template I just made.

**Comment by Nidaelie** [comment]
atm9 removed all rub and oculus mods and still the client crash

**Comment by cameronkh** [comment]
I was also using ATM9 the mods I have disabled are Iceberg, Rubidium, and Rubidium Extra. After I disabled those mods I haven't had any crashes.

**Comment by Nidaelie** [comment]
updated gadgets mod cause i had the rest removed and continues crashing...

**Comment by Direwolf20-MC** [comment]
This looks like a different crash. I’ll investigate.

**Comment by Nidaelie** [comment]
[crash-2023-09-21_21.29.20-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/12691140/crash-2023-09-21_21.29.20-client.txt)

**Comment by Direwolf20-MC** [comment]
I couldn't replicate the crash but added some code that should help prevent it. It'll go into the next version (1.0.2)
