### ISSUE TITLE
ATM 8 Issue

### ISSUE THREAD

**Issue by 00Bluwastakensonowitsthis** [Direwolf20-MC/BuildingGadgets2#27]
3.16.2-build_22

After placing a residence (MC colony mod), we tried destroying the buildind which then crashed our game.

Copy paste a level 1 residence from the MC colony mod, then try to destory stairs and or furnace

**Log Files** 

[crash-2023-09-16_23.12.22-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/12641594/crash-2023-09-16_23.12.22-client.txt)
[crash-2023-09-16_23.18.47-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/12641595/crash-2023-09-16_23.18.47-client.txt)
[crash-2023-09-16_23.07.31-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/12641596/crash-2023-09-16_23.07.31-client.txt)

**Comment by Direwolf20-MC** [comment]
This is the GitHub for building gadgets 2 which is only for 1.20.1. At this time building gadgets one isn’t really supported anymore. Sorry!
