### ISSUE TITLE
[suggestion] water placement feature

### ISSUE THREAD

**Issue by JJSax** [Direwolf20-MC/BuildingGadgets2#29]
Watching the spotlight I had this idea.  Having 2 buckets in your inventory would allow you to place water for free (since you could just make an infinite source anyway.)  This would solve the need for an entire inventory of buckets that don't stack.  Currently filling a large area with water would take forever and be frustrating. 

Alternately, could do the same thing if standing in an infinite water source.

**Comment by Direwolf20-MC** [comment]
Not a bad idea but then I’d have to special case water since it’s the only thing that behaves that way. Also some mod packs disable infinite water. I’ll likely just leave it as is :)
