### ISSUE TITLE
Crash when use Fade building render

### ISSUE THREAD

**Issue by Fiocher** [Direwolf20-MC/BuildingGadgets2#3]
Forge 47.1.44 / OptiFine l6_pre6
It should be OpiFine's problem.
[crash-2023-08-18_14.11.22-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/12376039/crash-2023-08-18_14.11.22-client.txt)

**Comment by MichaelHillcox** [comment]
Please try again without Optifine

**Comment by Direwolf20-MC** [comment]
Likely optifine related. Please re-open if you feel this is not the case
