### ISSUE TITLE
Apotheosis anvil

### ISSUE THREAD

**Issue by EndangeredNayla** [Direwolf20-MC/BuildingGadgets2#30]
**Building Gadgets Version**
1.0./

**Describe the bug**
cant paste apotheosis anvil

**To Reproduce**
1).copy apotheosis anvil + ( some blocks )
2). Paste apotheosis anvil and the hloxka
3) paste stops exception.hit

**Expected behavior**
It pastes the full thing

**Screenshots**

**Log Files** 
Crash logs are extremely important in helping me figure out how I DireDerped.

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by Direwolf20-MC** [comment]
It will be fixed in the next version - thanks for reporting! :)
