### ISSUE TITLE
[1.19.2] Gadgets always shows red and cannot be used outside of creative

### ISSUE THREAD

**Issue by Darkmega18** [Direwolf20-MC/BuildingGadgets2#32]
**Building Gadgets Version**
buildinggadgets-3.16.2-build.22+mc1.19.2.jar

**Describe the bug**
When I made a gadget and was hoping to use it in my survival world I discovered that even after charging it to around half energy O couldn't replace any blocks with cobblestone. The gadgets work fine in creative which is where I had been using them to quickly make test platforms while building my modpack and testing things.
However now that I'm playing they seem completely non-functional.

**To Reproduce**
Just try to literally use the gadget in MC 1.19.2... with 320+ mods installed. :V

**Expected behavior**
Gadget should work, whether or not I'm in or out of creative mode.

**Screenshots**
Gadget is charged.
![image](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/8104689/3c3a4b28-4110-40fb-975a-1205db1167ed)

but still cannot replace.
![image](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/8104689/429cf9f6-94ed-4166-b5f7-a84b111da387)

but it'll work just fine in creative.
![image](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/8104689/3ddcd7db-835c-4c9e-a8d7-c26ede53a833)

**Log Files** 
There isn't a crash just a bug. :V

Rubidium hasn't made me crash while using it in creative for massive areas, so I think I'm fine on that front.

**Comment by Direwolf20-MC** [comment]
Is it possible theres some kind of spawn protection or chunk protection going on there? It must be that or a mod conflict, otherwise we'd be getting flooded with these kinds of reports :). 

Also, BuildingGadgets 1 is not really supported anymore, its too old and janky. Sorry!

**Comment by Darkmega18** [comment]
oh? what? theres a two?! O_o

**Comment by Direwolf20-MC** [comment]
Yup but it’s 1.20.1 and up only. Sorry!

**Comment by Direwolf20-MC** [comment]
Sorry but that seems like an issue on their end :)

**Comment by Darkmega18** [comment]
:<
