### ISSUE TITLE
Doors not placing in 1.0.3 version of BG2

### ISSUE THREAD

**Issue by Gloval** [Direwolf20-MC/BuildingGadgets2#35]
**Building Gadgets Version**
1.0.3

**Describe the bug**
All doors are not being placed when pasting in a schematic. Doors are listed in the Material List.   Also of note and possibly related, trap doors paste into the world in a down, horizontal, state regardless of state when copied. 

**To Reproduce**
Paste in a schematic with doors in it. 

**Expected behavior**
All doors should be placed in. 

**Screenshots**

**Log Files** 
No crash

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by AceDrago** [comment]
also the campfires if extinguished with shovel are not staying unlit and when pasted become relit as well.

**Comment by Direwolf20-MC** [comment]
Doors are blacklisted in the mod - they are just weird things that are hard to place due to being 2 blocks in reality. 

I’ll look at the state issues though :)

**Comment by Direwolf20-MC** [comment]
Trapdoor shares its properties with other blocks that are less safe to copy, so I'm err'ing on the side of safety here. Sorry! Gotta leave trap doors as they are.
