### ISSUE TITLE
Using Template Manager to copy contents of Copy/Paste Gadget to Clipboard Fails

### ISSUE THREAD

**Issue by StanleyMcClister** [Direwolf20-MC/BuildingGadgets2#36]
**Building Gadgets Version**
1.0.5

**Describe the bug**
When using the template manager to copy the contents of the copy and paste gadgets to my clipboard, the operation returns a semi-empty json string. The json string contains properties but not values. 

**To Reproduce**
In DW 1.20 I loaded a superflat world to do some building. After copying a structure, i went to the template manager and pressed copy. To copy the contents of the build to my clipboard. I pasted to VS Code and the results are as follow: 
{
  "name": "",
  "statePosArrayList": "{}",
  "requiredItems": {}
}
**Expected behavior**
I should be able to copy the contents of a copy from a copy and paste gadget to my clipboard so that i can save it for later. 

Please note: 
I am using Embeddium for 1.20 (the rewrite for Rubidum) I have not had any issues with the gadgets other than not being able to copy to clipboard, which is something embeddium shouldn't mess with. 

(Edit: Removed screenshot)

**Comment by Direwolf20-MC** [comment]
Are you sure there’s data on the gadget? If you put the gadget in paste mode does it render in game?

**Comment by moomoo84** [comment]
I think you may be trying to copy the schematic using the previous method. As in adding the copy paste tool and nothing more, then clicking on copy. This has now changed. Watch dires BG2 spotlight for the new method.
