### ISSUE TITLE
Destruction gadget Atm9

### ISSUE THREAD

**Issue by CrimsonExe** [Direwolf20-MC/BuildingGadgets2#37]
**Building Gadgets Version**
Atm9 (not home to look at the mod version?)

**Describe the bug**
The destruction gadget is able to destroy players bases that are in claimed chunks on atm9

**To Reproduce**
Have the 2nd player claim land and have the first player use the gadget to destroy the claimed land. The 2nd player doesn't have to be a ally or on a team for the 1st player to destroy their base

**Expected behavior**
I expected that this tool wouldn't be allow to destroy players claimed chunks this is very detrimental for servers

*

**Comment by Direwolf20-MC** [comment]
I can't duplicate this bug in the latest version of the mod, so it must have been fixed by now :). Let me know if its still happening on the latest version please

**Comment by FoxMcloud5655** [comment]
This still happens.  We're using FTB Chunks and all tools bypass claims.  Versions of both mods:
FTB Chunks: 2001.2.3
Building Gadgets 2: 1.0.6

**Comment by Direwolf20-MC** [comment]
Reopened. Will investigate further.

**Comment by Direwolf20-MC** [comment]
This should be fixed in later versions :)
