### ISSUE TITLE
Cut and paste tool crashes game (client sided)

### ISSUE THREAD

**Issue by MarlinL1304** [Direwolf20-MC/BuildingGadgets2#39]
**Building Gadgets Version**
Building Gadgets 2 version 1.03

**Describe the bug**
Using the cut and paste tool will straight up crash my game client sided but not server sided. When using the tool, it will only cut half or less of whatever it is I am trying to cut while making me lose the rest of the buildings blocks I am cutting after the crash.

**To Reproduce**
Play on All The Mods 9 version 0.1.12 and whilst on the server, use the cut and paste tool to outline whatever it is to cut then cut it from the GUI interface (Not by key-bind). 

**Expected behavior**
I expected to be able to use the tool without any issues and be able to move whatever I wanted but I guess not.

**Log Files** 
Crash log: [crash-2023-10-12_12.23.36-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/12886764/crash-2023-10-12_12.23.36-client.txt)

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by Direwolf20-MC** [comment]
You're on a pretty old version of building gadgets, can you try upgrading to a newer one ? I'm pretty sure this has been fixed.
