### ISSUE TITLE
Crash when exchanging Spawner

### ISSUE THREAD

**Issue by PaulEllis2001** [Direwolf20-MC/BuildingGadgets2#4]
In All The Mods 9 version 0.0.53, when using the exchanging gadget, enchanted with silk touch, on a spawner, the game crashes. Attached is the crash report generated.

I had dirt selected to replace the spawner with, Affect Block entities was the default value as I had just crafted the gadget. I had gone into my inventory while the exchange was happening.

[crash-2023-08-19_15.23.26-server.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/12386737/crash-2023-08-19_15.23.26-server.txt)

**Comment by Direwolf20-MC** [comment]
Thanks for the report I’ll investigate :)

**Comment by Direwolf20-MC** [comment]
I couldn't reproduce this crash, however I added some code that should protect against it.
