### ISSUE TITLE
(Feature Return Request) - Block MOD listed in Materials list

### ISSUE THREAD

**Issue by Gloval** [Direwolf20-MC/BuildingGadgets2#42]
**Building Gadgets Version**
1.0.5

**Describe the bug**
In Building Gadgets, when you pulled the Materials list the lint showed the Mod and the block for each required resource.
In Building Gadgets 2 only the block is listed.
Would also like to see the Copy button return to the Materials list window in the UI for easier collect of the data to share, 

**To Reproduce**
Pull Materials list details from the gadget.

**Expected behavior**
Mod and Block details in list.

**Screenshots**
(https://imgur.com/a/tUtZfEd)

**Log Files** 
No Crash

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by Direwolf20-MC** [comment]
Will be part of the next version, thanks! :)
