### ISSUE TITLE
Dupe with Sophisticated Backpacks

### ISSUE THREAD

**Issue by ChosenArchitect** [Direwolf20-MC/BuildingGadgets2#44]
**Building Gadgets Version**
buildinggadgets2-1.0.5.jar

**Describe the bug**
When using sophisticated backpacks and having the items in the backpack and in inv, if I build with the building gadget and then undo it will dupe the contents of the backpack into my inventory. (the backpack was obtained by killing a mob with the backpack if that matters aka not a crafted one)
SophisticatedBackpacks Mod version
sophisticatedbackpacks-1.20.1-3.18.65.935.jar

Clip of issue:
https://clips.twitch.tv/ExuberantDullSharkAliens-f5ghKrLMxnRLZ2Wv

**Expected behavior**
Not to dupe

**Log Files** 
[debug.log](https://github.com/Direwolf20-MC/BuildingGadgets2/files/13207674/debug.log)

**Modpack**
CMA: Chunk by Chunk
https://legacy.curseforge.com/minecraft/modpacks/chosens-modded-adventure-chunk-by-chunk

Forge Version: Forge - 47.1.3

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by Direwolf20-MC** [comment]
Try as I might I can't get this to repeat :). Is it possibly some other mod causing it? Thats super weird.

**Comment by Direwolf20-MC** [comment]
Actually - correction - Mikey pointed out that it only happens if the backpack is in your armor slot, and not the curios slot. Fixed now :) thank you!

**Comment by ChosenArchitect** [comment]
No problem bud!
