### ISSUE TITLE
Anchor Persistence

### ISSUE THREAD

**Issue by Gloval** [Direwolf20-MC/BuildingGadgets2#47]
**Building Gadgets Version**
1.0.5

**Describe the bug**
Once Anchored the Copy Paste Tool should preserve the Anchor point after pasting in the event of subsequent pastes over the same structure to build more or complete build if more blocks or energy are needed.

**To Reproduce**
Anchor a build, Paste it, See that Anchor point was not preserved.

**Expected behavior**
Once Anchored the Copy Paste Tool should preserve the Anchor point.

**Comment by Direwolf20-MC** [comment]
Gave this a try and decided I liked it :)
