### ISSUE TITLE
Crash to desktop

### ISSUE THREAD

**Issue by Gloval** [Direwolf20-MC/BuildingGadgets2#48]
**Building Gadgets Version**
1.0.5

**Describe the bug**
Some PC builds will crash to desktop if Shaders are enabled and the Copy/Paste or Cut/Paste gadget are put into Paste mode.  When the Ghost image attempts to render the game crashes.

**To Reproduce**
Enable Shaders, Load a schematic into the Copy/Paste Gadget or capture a build int he Cut/Paste Gadget then put the Gadget into Paste Mode.  As soon as the Ghost image attempts to render the game crashes to desktop.

**Expected behavior**
No crash or at least a ToolTip on the gadgets to disable Shaders before placing in Paste mode.

**Log Files** 
[Crash logs are extremely important in helping me figure out how I DireDerped.](https://drive.google.com/file/d/1OXa2qn8ny4pqpvOkOyidCpl8cZVrKAF1/view?usp=drive_link)

It was noticed that this doe not occur on all PC builds.  A System with a 3080TI is able to render with shaders a Build Ghost image with no issues but a 3060 crashes every time the render is attempted.

This is while using Embeddium(embeddium-0.2.5+mc1.20.1.jar) and Rubidium_Extra(rubidium-extra-0.5.3+mc1.20.1-build.106.jar).

**Comment by Gloval** [comment]
Tried removing Rubidium_Extra but got the same crash.

**Comment by Direwolf20-MC** [comment]
Can you try removing Embeddium and any shaders and see if you still crash?

**Comment by Gloval** [comment]
If I disable the shaders it works fine and as expected. Again, just thought you may want to make a comment about it in your current LetsPlay and or a tool tip on the 2 gadgets.

**Comment by Direwolf20-MC** [comment]
Cool thanks ;) yea unfortunately it’s rubidium related :(.
