### ISSUE TITLE
Exchanging Gadget will not effect blocks around the clicked block

### ISSUE THREAD

**Issue by mich561d** [Direwolf20-MC/BuildingGadgets2#49]
**Building Gadgets Version**
Building Gadgets 2 v1.0.5 (Modpack: FTB Presents Direwolf20 1.20 1.4.0)

**Describe the bug**
Using the exchanging gadget to exchange blocks when used on the same type as the selected block type won't affect blocks around it even if range is big enough.

**To Reproduce**
1. Place a 5x5 square of dirt
2. Replace the middle 1x1 with sand
3. Set the chosen block of the exchanging gadget to sand and the range to 5 (Fuzzy and connected area doesn't matter)
5. Try to exchange the blocks by clicking on the middle (sand)
6. Verify the dirt is not exchanged to sand

**Expected behavior**
The rest of the 5x5 should be exchanged to sand (this was the behavior of Building Gadgets 1)

**Comment by Direwolf20-MC** [comment]
Yea I think I'm fine with that change :)
