### ISSUE TITLE
[1.20.1] Copy/Paste Gadgets Crash 

### ISSUE THREAD

**Issue by lays24mc** [Direwolf20-MC/BuildingGadgets2#5]
I am currently playing my modpack "Mining with friends" and have included your mod. Firstly, thank you for this great mod :)

I tried a little bit today and unfortunately the game always crashes me as soon as I want to paste a copied structure on a piece of paper in the template. At first, I thought that structures from old versions no longer work, but the same problem also exists with structures copied in 1.20.1. 

Here the Crashlog: https://pastebin.com/jm7Zwfd5 
Forge: 47.1.3
Building Gadget 2: 0.1.1

**Comment by Direwolf20-MC** [comment]
Can you let me know what’s happening in the template manager when this crash happens ? Is there an item in the top and bottom slot and can you post the paste you’re trying to put in?

**Comment by lays24mc** [comment]
I have found my issue. Apparently only old code does not work, and I had overlooked that the new code was not even in my "paste" in the second attempt. New structures (1.20.1) can be pasted. I apologize for the misinformation.

I guess the old templates don't work. That would be my old code:

https://pastebin.com/WRMDHrGG

**Comment by Direwolf20-MC** [comment]
It’s definitely on my list to support old pastes :) and I should still prevent crashes with the old paste data either way. 

Can you put the old paste data here so I can test with it ?

**Comment by lays24mc** [comment]
I don't know why, but Pastebin seems to have just removed the code again -.-

I hope my Github link to the code fits as well: https://github.com/lays24mc/Building-Gadget-Codes/blob/main/Codes/oak_tree_1.json

**Comment by Direwolf20-MC** [comment]
Thanks! I’ll get working on it shortly :)

**Comment by Direwolf20-MC** [comment]
Is *this* your card? :)

![image](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/39863894/e539f89c-72b2-417c-8d3a-97b8a99b529a)

**Comment by lays24mc** [comment]
Exactly. Thanks a lot :)
