### ISSUE TITLE
Slabs placed with Building Gadget place at the wrong level when in horizontal row mode

### ISSUE THREAD

**Issue by ligerzero459** [Direwolf20-MC/BuildingGadgets2#50]
**Building Gadgets Version**
1.0.6

**Describe the bug**
When using the Building Gadget in horizontal row mode, slabs place at the incorrect level compared to the currently placed slab. It always builds down a half-level from a slab that's level with block level and then you cannot build a row on top with the gadget. Switching to "Place On Top" mode will leave a gap between the currently placed slab and the build slab, exactly on half-level up

**To Reproduce**
1. Place a slab, make sure you can build a torch on it. That means it's at the correct level
2. Use the Building Gadget in Horizontal Row mode, any range. New slabs should be a half-level down with no way to bring them up the half-level
3. Attempt to place another row on top, you'll be unable to do so
4. Switch to Place On Top mode, new preview should be a half level above

**Expected behavior**
Slabs should be built level with the starting slab

**Screenshots**
![javaw_pQd3MTS2OW](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/1093351/00c31fae-d02b-40bf-b98c-7968a4631fe1)
![javaw_bQYGo3ER7r](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/1093351/e9c6e7d3-0f26-42dd-a541-1d210d3ccef3)
![image](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/1093351/6126cf4f-2881-4204-9a13-330740b83e7e)
![image](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/1093351/c349c068-856e-42c4-9e23-e89b8ff225ee)

**Log Files** 
N/A

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by Direwolf20-MC** [comment]
Building gadgets can turn half slabs into double half slabs, so this is working as intended :).   When you place above, you're setting the block height at +1, so its working as intended as well.  Sorry! Its just the wonkiness of half slabs!
