### ISSUE TITLE
Client Crash with builder tool on rendering Belt from create.

### ISSUE THREAD

**Issue by XikoCat** [Direwolf20-MC/BuildingGadgets2#51]
**Building Gadgets Version**
1.0.6

**Describe the bug**
Client crash when trying to render Belt block from Create using the Build Tool. I shift clicked the belt on accident when trying to place a normal solid block while playing on a server. The server is fine, but the client crashes on join because the tool is the selected item and is trying to render the block.

**To Reproduce**
- Sneak-click Belt with shaft block from Create, using the build tool

**Expected behavior**
Either not render the block or not allow selecting it at all.

**Screenshots**
https://i.imgur.com/U5vtScG.png

**Log Files** 
https://mclo.gs/GztgDLC

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

It crashed with embedium, then I disabled all mods related to it and it still crashed.

**Comment by XikoCat** [comment]
The item and NBT for reference:
![image](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/14017806/0c78314f-c2c5-4c72-b041-f3a96886f9ba)

**Comment by Direwolf20-MC** [comment]
I can't reproduce this in dev environment - can you test without embeddium and let me know if it crashes still?
