### ISSUE TITLE
Server Crash when pasting an enderio fluid conduit

### ISSUE THREAD

**Issue by MahindraPersaud** [Direwolf20-MC/BuildingGadgets2#52]
**Building Gadgets Version**
1.0.6

**Describe the bug**
Attempted to Cut and paste a few tools while following along Dire's wither Farm build. Cut the following blocks:
- Blue Shield Template (RFToolsBuilder)
- Laser Node (LaserIO)
- Laser Drill (Industrial Foregoing)
- Fluid Laser Base (Industrial Foregoing)
- Ender Tank (EnderTanks)
- Basic Fluid Tank (Mekanism)
- Fluid Conduit (EnderIO)

**To Reproduce**
1. Create a system with an enderio fluid conduit.
2. Attempt to copy that system
3. Paste that system (this is when the crash occurs)

**Expected behavior**
EnderIO fluid conduit would copy correct

**Screenshots**
![2023-11-16_13 40 22](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/6376099/968caccf-f4cd-4d9d-8aa8-f95949008472)

**Log Files** 
[crash-2023-11-16_12.37.23-server.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/13382204/crash-2023-11-16_12.37.23-server.txt)
[crash-2023-11-16_12.38.25-server.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/13382205/crash-2023-11-16_12.38.25-server.txt)

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by Direwolf20-MC** [comment]
EnderIO cables are very special and unique - I'm not entirely surprised that they don't work too well unfortunately. I'll see if I can add support, but just like AE2 cables, they are just super customized blocks.
