### ISSUE TITLE
Exchanging Gadget doesnt like End Block from ManyIdea

### ISSUE THREAD

**Issue by willtarax** [Direwolf20-MC/BuildingGadgets2#53]
**Building Gadgets Version**
Put the version of Building Gadgets 2 here.  1.0.5

**Describe the bug**
A clear and concise description of what the bug is. When trying to load the end block from ManyIdeas into the exchanging gadget, it crashed my client side

**To Reproduce**
Steps to reproduce the behavior: Place the end block, shift right click with Exchanging gadget and bingo bango bongo client side crash

**Expected behavior**

**Screenshots**

**Log Files** 
Crash logs are extremely important in helping me figure out how I DireDerped.

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by Direwolf20-MC** [comment]
I'll look into supporting this
