### ISSUE TITLE
Crash on use ( Exchange Gadget 

### ISSUE THREAD

**Issue by Zelioth** [Direwolf20-MC/BuildingGadgets2#54]
**Building Gadgets Version**
1.0.6

**Describe the bug**
 building gadgets mod, specifically the exchange gadget causes the game to crash as well as the undo function of the building gadget

**To Reproduce**
[crash-2023-11-20_17.24.02-server.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/13430844/crash-2023-11-20_17.24.02-server.txt)

 building gadgets mod, specifically the exchange gadget causes the game to crash as well as the undo function of the building gadget

**Comment by Direwolf20-MC** [comment]
Are you exchanging functional storage drawers ? Or maybe have some in your inventory?  

If so put them away and see if the crash stops. 

I think I see what’s happening. It’s treating storage drawers in your inventory like a backpack and trying to put items in them.
