### ISSUE TITLE
Key Binding

### ISSUE THREAD

**Issue by Plundee** [Direwolf20-MC/BuildingGadgets2#55]
**Building Gadgets Version**
BuildingGadgets2-1.0.6

**Describe the bug**
Wanting to put my build copy and put it in mirror mode, I watched them control and learned that with the key "range" we could do it but this key does nothing even by changing it

**To Reproduce**
1. Copy a construction 
2. enter paste mode
3 . used the "range" key

**Expected behavior**
See my construction in mirror mode of what I copy 

**Screenshots**

![image](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/151777860/a92751ae-4451-4847-9d07-041e8135e258)

**Comment by Direwolf20-MC** [comment]
Ah sorry, Range is only used for the building and exchanging gadget.  It has no functionality for the copy/paste gadget. Sorry!
