### ISSUE TITLE
Exchanging Gadget Bricking World

### ISSUE THREAD

**Issue by saberslayergg** [Direwolf20-MC/BuildingGadgets2#56]
**Building Gadgets Version**
1.06

**Describe the bug**
Upon selecting a block with the exchanging gadget the entire game closed and I can no longer access my Allthemods 9 server. It appears to be having issues with the render pipeline pointing to a null value, I was attempting to select a connected polish blackstone block rom the rechiseled mod
**To Reproduce**
Select chiseled blackstone with exchanging gadget
crash to desktop

**Expected behavior**
Select Chiseled blackstone with exchanging gadget
Render applicable exchanging area

**Screenshots**

**Log Files** 
https://pastebin.com/H4X8BJME

https://pastebin.com/BqntZ4f1

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by Direwolf20-MC** [comment]
I’m seeing rubidium in the crash log. Can you try removing it and see if you crash?
