### ISSUE TITLE
Crash on loading schematics following DIrewolf20 series -Create workshop

### ISSUE THREAD

**Issue by abdullamu** [Direwolf20-MC/BuildingGadgets2#57]
I play on All the mods 9, when i load the schematic Create workshop it crash while rendering blaze..
Now i cant load into my save.

https://pastebin.com/2fXezkak

**Comment by Direwolf20-MC** [comment]
It looks like you have rubidium installed. Please remove it and if it still crashes let me know.

**Comment by abdullamu** [comment]
actually after disabling shaders { red the previous closed post and did the same} everything works fine. Thank you dire
