### ISSUE TITLE
Applied Energistics 2 blocks not rotated after paste

### ISSUE THREAD

**Issue by jerry1333** [Direwolf20-MC/BuildingGadgets2#58]
**Building Gadgets Version**
buildinggadgets2-1.0.6.jar from [FTB 1.20.1 pack](https://www.feed-the-beast.com/modpacks/119-ftb-presents-direwolf20-120) v 1.7.0

**Describe the bug**
This happens to Applied Energistics 2 but it may be about other mod blocks too. Some blocks are not rotated properly after Cut Paste operation and setup no longer works.

**To Reproduce**
1. Build  for example https://guide.appliedenergistics.org/1.20.1/example-setups/advanced-certus-farm
![2023-11-26_09 57 31](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/984193/83e1b51e-671d-4254-83ca-de1a4c8ccb0c)
![2023-11-26_09 57 21](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/984193/45450782-bdbd-4683-8521-49aeb3fcb6e9)

2. Cut it with Cut Paste Gadget
3. Before pasting it rotate it like 90 / 180 / 270 deg.
4. Paste it
![2023-11-26_09 58 29](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/984193/aa54e13e-54ac-4883-b93f-f13509629cb7)
![2023-11-26_09 58 08](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/984193/fffcec18-b4a9-4d43-b1e0-8ce815de3d9f)
![2023-11-26_09 58 14](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/984193/ff3a875e-90ef-4ad7-bf4d-b7bfd410377a)

**Expected behavior**
After rotating all blocks should rotate.

**Screenshots**
Included in reproduce steps.

**Log Files** 
No crash at this time

**Comment by Direwolf20-MC** [comment]
Agree with Mikey, the rotation is probably handled differently than vanilla blocks (Like chests and oak) so it may not be easy to support. We'll look into adding a way for mod authors to 'tell' our mod how to support rotation, but that'll be a complex solution
