### ISSUE TITLE
Cut/Paste tool crashes the game when cutting a running laserio setup

### ISSUE THREAD

**Issue by PianoHallvard** [Direwolf20-MC/BuildingGadgets2#6]
Figured something like that would happen
Anyway, here's the pastebin https://pastebin.com/Uq58H0mp

**Comment by Direwolf20-MC** [comment]
Can you try doing it without any rendering mods like Sodium?

**Comment by ChosenArchitect** [comment]
I had the same Crash and disabled Rubidium, it fixed the crash when cutting an inventory with items in it.

**Comment by Direwolf20-MC** [comment]
Yea, I'll see what I can do to avoid crashes with those mods. I'll have to add them to my dev environment to figure out whats happening

**Comment by Direwolf20-MC** [comment]
I made an issue over on their repo asking to work together to resolve it - I'll close this one for now.
