### ISSUE TITLE
Game crash on interaction between Exchanging gadget and Occultism mod storage

### ISSUE THREAD

**Issue by NoodleRev** [Direwolf20-MC/BuildingGadgets2#60]
Building Gadgets Version 1.0.6
Playing on All The Mods 9 Version 0.2.28

Using the Exchanging Gadget on Occultism's Storage Actuator will crash the game. From then on, loading into the world will continue to crash the game. 
I've been playing on a server that offers a secondary world (Hosted separately) but with a shared inventory. Logging into this secondary server with the exchanging gadget still in the inventory continues to crash the game when loaded in.

-Use an exchanging gadget on Occultism's Storage Actuator.
             (Note: Unsure if this was a right-click or a shift + right-click)

Expected behavior:
-Either have no interaction with the storage actuator,
-Or pick the storage actuator up.

Log Files: https://file.io/EN0QmSLBk5Zc

Rubidium Note:
ATM9 is using Embeddium rather than Rubidium, however the crash still persisted when Embeddium was removed.

**Comment by Direwolf20-MC** [comment]
Sorry I can't reproduce this, and the log file has expired. Please let me know if its still happening
