### ISSUE TITLE
Building Gadgets 2 crash

### ISSUE THREAD

**Issue by Lucym1997** [Direwolf20-MC/BuildingGadgets2#61]
Building Gadgets 2 Version: 1.0.6

**Describe the bug**
When i use cut and paste gadget on a structure, i crash and i had to remove all the building gadgets in my inventory to enter in the server (remove only cut and paste wasn't enough)

[crash-2023-12-17_00.41.37-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/13694315/crash-2023-12-17_00.41.37-client.txt)

**Comment by Direwolf20-MC** [comment]
Can't reproduce, can you tell me what block you were copying?
