### ISSUE TITLE
Client crashes when copy/paste gadget is selected

### ISSUE THREAD

**Issue by LyraelRayne** [Direwolf20-MC/BuildingGadgets2#62]
**Building Gadgets Version**
1.0.6 (AllTheMods 9)

**Describe the bug**
Whenever I select the copy/paste gadget

**To Reproduce**
Not sure. It crashes every time open the gadget but it didn't initially. I think it started to happen
after selecting an area.

**Expected behavior**
Not crashing

**Log Files** 
https://mclo.gs/MoOGsqE

Rubidium is not installed.

**Comment by Direwolf20-MC** [comment]
Sorry can't be sure which block is causing the crash, please let me know if you find out what block is causing it :)
