### ISSUE TITLE
Pasting Growthcraft grapes crashes the game and corrupts the world file

### ISSUE THREAD

**Issue by PsiQss** [Direwolf20-MC/BuildingGadgets2#63]
**Building Gadgets Version**
Building Gadgets 2 1.0.6

**Describe the bug**
After pasting Growthcraft grape crops in Creative Mode the game crashes and corrupts the save file. Happens with both copy/paste and cut/paste gadget.

**To Reproduce**
1. Be in creative mode
2. Plant and grow Growthcraft's grapes.
3. Copy/Cut the grape crop blocks.
4. Paste copied blocks

I'm assuming it is not possible to reproduce in survival, as the crop blocks cannot be present in the inventory (and therefore would not be placed)

**Expected behavior**
The grape crop blocks should not have been copied. After some digging in the code I see that there is a deny list being prepared, albeit statically.
Maybe there should be a tag that could be used in other mods to blacklist them?

**Log Files** 
[crash-2023-12-22_00.17.24-server.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/13751648/crash-2023-12-22_00.17.24-server.txt)

**Comment by Direwolf20-MC** [comment]
Looks like growthcraft relies on the property of 'age' for its rendering, and thats whats throwing it off :).  For now I agree, try not to copy those crops, and I'll see if theres a way to fix the crash. Thanks!
