### ISSUE TITLE
[Suggestion] Hide energy tooltip when max energy is set to 0

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Direwolf20-MC/BuildingGadgets2#72]
My pack doesn't use RF, so exchangers are free. I set max energy and all RF consumption values to 0 in the config. 

The tooltip of all 5 gadgets now say "Energy: 0.0/0.0" which is not helpful information and may confuse players.

**Comment by Direwolf20-MC** [comment]
Will add to the 'nice to have' feature list :) thanks!
