### ISSUE TITLE
[Suggestion/Enhancement ] Random mode placement

### ISSUE THREAD

**Issue by DevDyna** [Direwolf20-MC/BuildingGadgets2#73]
## Description
A new mode for all gadgets : **Random Placement** , when enabled it *"process blocks"* with a chance to *"execute them"*

Can be very useful use it to apply details on big structures without need other mods like worldedit , effortless , etc...

**Comment by Direwolf20-MC** [comment]
Sorry not quite an intended feature, I'd suggest maybe randomly spamming the exchanger around :)
