### ISSUE TITLE
[Bug] Not-So-Equal exchange with Create

### ISSUE THREAD

**Issue by andr9528** [Direwolf20-MC/BuildingGadgets2#75]
**Building Gadgets Version**
buildinggadgets2-1.0.6

**Create Version**
create-1.20.1-0.5.1.f

**Describe the bug**
When chosing a casing block from Create, which has a shaft inside the casing block, the casing block is spend to build/exchange the block, when a shaft is what is normaly palced and then disguised as the casing.

**To Reproduce**
- With a Exchanging/Building tool, choose a shaft currently encased in some casing (Andesite/Brass).
- Exchange or build some block.
- Notice that the casing is used.
- Break the new block, receving the expected shaft.
- Wonder about your not-so-equal exchange.

**Expected behavior**
The 'block' should spend shafts, not casings, and be disguised as the casing.

**Comment by Direwolf20-MC** [comment]
This is likely just a weird side-effect of how Create handles its blocks.  I don't really think theres a good solution to it, without special casing everything :(.
