### ISSUE TITLE
Building Gadget allowing placement of water in nether

### ISSUE THREAD

**Issue by scottweaver429** [Direwolf20-MC/BuildingGadgets2#78]
**Building Gadgets Version**
3.13.2

**Describe the bug**
When using the building gadget to place coral fans in the modpack Vault Hunters, it places water with them, even in the nether, allowing for water in the nether.

**To Reproduce**
Steps to reproduce the behavior: Use the building gadget to place fire coral fans while running the modpack 'Vault Hunters.'

**Expected behavior**
I expected the fans to be placed without water since I did not shift-right-click the coral while it was even in water.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
![2024-02-12_20 04 57](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/159865495/9f58b640-dd47-493b-8e5f-dde3f6e4bfa9)

**Log Files** 
Crash logs are extremely important in helping me figure out how I DireDerped.

**No crashes involved**

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by Direwolf20-MC** [comment]
Seems to be resolved ;) I must have fixed this at some point heh
