### ISSUE TITLE
Crash on Copy

### ISSUE THREAD

**Issue by Karmas-Daemon** [Direwolf20-MC/BuildingGadgets2#79]
Occurred on a Server
ATM9 2.43 1.20.1
Mod V1.0.6

I am experiencing an issue with the copy-paste gadget. It seems to be crashing the server upon attempt to copy a block of cobbled deepslate in the Void dimension ("the-beyond" from allthemodium). 

Crashed twice. On each attempt, attempted to copy a block of deepslate in the void dimension. For my third attempt, I went to confirm it worked in the overworld. It does. Then returned to void dimension, re attempted the deepslate, user was timed out from server, but server did not crash. Relogged to find that the copy worked and could see a highlighted section extending into infinity. 

This appears to be caused by the copy-paste gadget attempting to select all the blocks from the previously saved point in the overworld, to the point selected in the Void dimension. Have not attempted, but this is likely recreate-able between any two dimensions. Should there not be a function to determine the previous copy selection dimension, to prevent this from occurring?

Here are the two crash reports:
[crash-2024-02-16_01.24.47-server.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/14304254/crash-2024-02-16_01.24.47-server.txt)
[crash-2024-02-16_01.37.01-server.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/14304255/crash-2024-02-16_01.37.01-server.txt)

**Comment by Direwolf20-MC** [comment]
Hrm yea that could be what its trying to do, but it *should* be hitting a limit. 

As a workaround for now, try clearing the saved positions on the copy GUI there should be a button for it. 

![image](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/39863894/f1523857-1582-42cc-adb5-1f29d87e627a)

**Comment by Direwolf20-MC** [comment]
Update: Tested, and yea it hits a limit - after calculating how many blocks are inside the thing. So I guess I should do a simpler calculation to limit it. I'll add this change for 1.20.4
