### ISSUE TITLE
Cut/Paste Tool replaces Bedrock

### ISSUE THREAD

**Issue by foxjordan** [Direwolf20-MC/BuildingGadgets2#8]
All the Mods 9 V0.0.55
Building Gadgets 2 V0.1.1

**Comment by ChosenArchitect** [comment]
Can confirm :D

**Comment by foxjordan** [comment]
All the Mods 9 V 0.0.55
Building Gadgets 2 0.1.1

**Comment by Direwolf20-MC** [comment]
Woops! Thanks for the report I'll get that sorted in the next release :D. For now avoid falling into the void heh
