### ISSUE TITLE
Crash: Lets Do Vinery Conflict with Building Gadgets2 (1.20.1)

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [Direwolf20-MC/BuildingGadgets2#83]
**Building Gadgets Version**
1.0.6

**Describe the bug**
Vinery Window has a "part" property that Building gadgets don't anticipate and crashes servers when certain users log in. 
"The crash happened  because the game tried to use a setting on a block that doesn't exist in the Building Gadgets 2 (vinery windows "part" property)" ~Lets do discord

**To Reproduce**
Start server with Vinery, Lets Do Api and Building gadgets. 
User logs in, there's a vinery window that exists someplace. 
Crash, unable to reboot. 

**Expected behavior**
Vinery windows to not crash a server into the dust when playing with Building Gadgets installed. 

**Screenshots**

**Log Files** 
Crash logs are extremely important in helping me figure out how I DireDerped.
[message.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/14414353/message.txt)

**NOTE ON RUBIDIUM**
 We have Embeddium, does that do the same thing?

**Comment by Direwolf20-MC** [comment]
Hi there I think this is more on vinery’s side. They are trying to set the blockstate of my render block. They should test if the block is a vinery block before setting the blockstate :).
