### ISSUE TITLE
[Suggestion/Enhancement] Template Manager quick template import

### ISSUE THREAD

**Issue by DevDyna** [Direwolf20-MC/BuildingGadgets2#85]
## Description
A "limited" history to see all previous exported to clipboard
Something like a "backup" where the player can interact to instant-copy on clipboard to paste
Also if saved like hotbars.nbt (or any other format) , it will be customizzable from modpack dev example where there are many multiblock structures but on template manager there are already pre-fabricated all schematics to "quick import" on copy-paste gadget

**Comment by Direwolf20-MC** [comment]
Sounds interesting, but might be a lot of work to implement. I'll add it to the maybe pile :)
