### ISSUE TITLE
Exchanging Gadget not able to select Productive Bees Comb Blocks

### ISSUE THREAD

**Issue by Gloval** [Direwolf20-MC/BuildingGadgets2#86]
Working with BlueFireFox on the Direcord on an issue is discovered and wanted to submit a tkt on it for investigation.

Productive Bees Comb Blocks, which appear to be a normal block entity, produce an error when you attempt to select them, (See IMGUR gallery for screenshots.  I am able to select normal Vanilla Comb blocks with no issues.  I am also able to replace the PB Comb blocks with other blocks with no issue but not able to undo back.  No error is given when attempting to undo them back.  I am assuming it may be something do do with the raft of NBT and meta data attached to the PB Combs but though I'd submit it anyway incase there is some other tom foolery occurring.

https://imgur.com/a/mqVT7wf

**Comment by Gloval** [comment]
This was observed in ATM8, buildinggadgets-3.16.2-build.22+mc1.19.2

**Comment by micmou** [comment]
Cap you ever give dire a break xD I think between you and howie yall found most of the bugs :3

**Comment by Direwolf20-MC** [comment]
Can you let me know if this still happens in 1.21?

**Comment by Gloval** [comment]
Ok, in 1.21 it now does select all blocks, Productive Bees Comb blocks included, But when pasting in of the 6 blocks I placed down and copied, 2 each of 3 types, The 2st 2 pasted in properly but the other 4 did not.  The other blocks are Black, so their texture did not load properly which may be a Productive Bees interaction problem as much as a BG2 issue.  But they also, when block picked, show as the 1st type of comb not the type they were in the initial copy.  So I would say better but still not playing nice.
![2024-08-03_22 21 45](https://github.com/user-attachments/assets/00825f04-3ac1-4feb-9cad-ebf21ebe3347)

**Comment by Direwolf20-MC** [comment]
Its likely just a cross mod compat i won't be easily able to fix at this time, sorry!
