### ISSUE TITLE
Copy and paste gadget crash the game with create

### ISSUE THREAD

**Issue by THEFricadelle** [Direwolf20-MC/BuildingGadgets2#87]
**Building Gadgets Version**
Version 1.0.7

**Describe the bug**
When trying to paste a structure with create bolck the game crash, blocks like moving belt, belt, shaft and cogwheel but not funnel and gearbox.

**To Reproduce**
Copy some block (at least those i tried) from create by using the copy and paste tool
Change to paste mode
Game crash

**Expected behavior**
View of the copied build

**Screenshots**
Sorry the gearbox vid is not loading but it didnt crash the game
https://github.com/Direwolf20-MC/BuildingGadgets2/assets/162727367/767cfc64-e4f0-461b-8c1c-3882b7985aa0
https://github.com/Direwolf20-MC/BuildingGadgets2/assets/162727367/6d7feae5-66c8-4e8a-b5ae-79daf1466ded
![error message](https://github.com/Direwolf20-MC/BuildingGadgets2/assets/162727367/5074587b-8400-468e-b0c8-8303d0c4aca4)

**Log Files** 
Here are the crash report on the block i tested in the order i tell them in the description
[crash-2024-03-08_16.33.48-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/14540457/crash-2024-03-08_16.33.48-client.txt)
[crash-2024-03-08_16.42.55-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/14540460/crash-2024-03-08_16.42.55-client.txt)
[crash-2024-03-08_16.56.33-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/14540462/crash-2024-03-08_16.56.33-client.txt)
[crash-2024-03-08_17.09.09-client.txt](https://github.com/Direwolf20-MC/BuildingGadgets2/files/14540464/crash-2024-03-08_17.09.09-client.txt)

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by Direwolf20-MC** [comment]
Can you let me know if this happens in 1.21 still?

**Comment by THEFricadelle** [comment]
Hi, i can't test it for now since create mod is not yet in 1.21.

But i'll test it as soon as it is live for 1.21
