### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by TookUrSweetRoll** [Direwolf20-MC/BuildingGadgets2#9]
Building Gadget in "Build to Me", must be at X or Z +.300 (not .299) or it will put you in swim mode. If pillaring in the same mode with "Place On Top" ticked it will knock you off your pillar.

Also, the O is capitalized in Place On Top and the T is lowercase in Build to Me. Not sure which is correct, just noticed they are different.

I like the place/exchange animations but they are a touch slow for my taste. Will there be a config for this in the future?

**Comment by Direwolf20-MC** [comment]
For #1 I'd say don't pillar with place on top enabled :) just turn it if off if you intend to pillar up. 

I'll look at the capitalization issues. 

I'm considering speeding up the animation a smidge, you're not the first to mention it
