### ISSUE TITLE
Rendering Error Crash - 1.20.1 Forge

### ISSUE THREAD

**Issue by Endmateria** [Direwolf20-MC/BuildingGadgets2#90]
**Building Gadgets Version**
Building Gadgets 1.0.7
Forge Version 47.2.23
MC Version 1.20.1

**Describe the bug**
Game crashes almost consistently when I either use the build and replace gadgets, or even when I have them in my hand on the toolbar.

**To Reproduce**
Crashes are not 100% consistent.  Some games it crashes every time I use the building gadgets, then sometimes I can use the gadgets for a little while before it crashes.  It always produces the same hs_err report when it crashes though.  

**Expected behavior**

**Screenshots**

**Log Files** 
Crash logs are extremely important in helping me figure out how I DireDerped.
[hs_err_pid5852.log](https://github.com/Direwolf20-MC/BuildingGadgets2/files/14938620/hs_err_pid5852.log)
[latest.log](https://github.com/Direwolf20-MC/BuildingGadgets2/files/14938622/latest.log)

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by Direwolf20-MC** [comment]
Can you let me know if this happens without optifine?
