### ISSUE TITLE
mimic is null

### ISSUE THREAD

**Issue by HumanF91R** [Direwolf20-MC/BuildingGadgets2#91]
**Building Gadgets Version**
buildinggadgets-3.16.2-build.22+mc1.19.2

**Describe the bug**
Viewing a certain item from the building gadgets mod in creative menu or in jei immediately crashes the game.

**To Reproduce**
Steps to reproduce the behavior: Searching building gadgets in jei or going to building gadgets category in creative menu.

**Expected behavior**
Not to crash

**Screenshots**

**Log Files** 
https://pastebin.com/yE3df5cF

**NOTE ON RUBIDIUM**
Disabled Embeddium gave the same result.

**Comment by Direwolf20-MC** [comment]
Sorry that versions no longer supported
