### ISSUE TITLE
Server crash when use Undo button (1.19.2)

### ISSUE THREAD

**Issue by dhgameryt** [Direwolf20-MC/BuildingGadgets2#92]
**Building Gadgets Version**
buildinggadgets-3.16.2-build.22+mc1.19.2

**Describe the bug**
Server crash when use Undo button in building and copy/paste gadgets
This dont happen in the first time i use the gadgets, it start happen now

**To Reproduce**
I dont know if its reproducible but just use the undo button (im in a server)

**Expected behavior**
That the server dont crash

**Screenshots**

**Log Files** 
https://gist.github.com/dhgameryt/c0c801bf1860545ae63e92f8b401178e (lastest)
https://gist.github.com/dhgameryt/5dcaa12f5ff5d07109f0a6b90fea0254 (crash report)

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by Direwolf20-MC** [comment]
Sorry that versions no longer supported :(
