### ISSUE TITLE
Crashing with 1.20.6 Radial Menu

### ISSUE THREAD

**Issue by NicholasRB** [Direwolf20-MC/BuildingGadgets2#94]
Hey Dire, found out that opening the radial menu is crashing my game in with NeoForge 1.20.6 .

**Building Gadgets Version**
Version 1.2.0 for MC 1.20.6

**Describe the bug**
Crashing on attempt to open the radial menu

**To Reproduce**
Just press the radial menu button

**Expected behavior**
Menu opens

**Screenshots**
N/A

**Log Files** 
[latest.log](https://github.com/Direwolf20-MC/BuildingGadgets2/files/15281695/latest.log)

2nd log just in case: https://paste.ee/p/ymyZt

**NOTE ON RUBIDIUM**
Rubidium contains code that will crash many mods when used in conjunction with them. Unfortunately this includes Building Gadgets 2. There is absolutely nothing I can do on my side to prevent these crashes. If you're using Rubidium and your game crashes when rendering something, please try without rubidium before submitting a bug report.

**Comment by Direwolf20-MC** [comment]
Thanks for the report :) - Neoforge changed something and that class no longer exists. I've replaced it with something newer. Should be fixed in the next version, which i'll release now.
