### ISSUE TITLE
[Request] Would it be possible to make a converter for old schematics?

### ISSUE THREAD

**Issue by Kevin-Marsh** [Direwolf20-MC/BuildingGadgets2#96]
At the moment there is an extremely large catalogue of older builds since the scematics work interchangeably from 1.16-1.19. This broke in 1.20 though with your new setup for schematics files. Would it be possible to add something to the mod or even to have a small stand alone program that could take the older schematics and update it into the current format?

**Comment by Direwolf20-MC** [comment]
When I wrote the new schematic system I tested using the old ones and made a way for them to import. All but the very oldest ones should work. 

Can you give me an example of one that doesn’t so I can test it ?
