### ISSUE TITLE
Players kicked from server if copy-paste selection range is too large

### ISSUE THREAD

**Issue by Gibil** [Direwolf20-MC/BuildingGadgets2#97]
### Building Gadgets version

1.0.6

### Minecraft Version

1.20.1

### Forge Version

47.2.16

### Modpack & Version

ATM9 - 0.2.34

### Do you have optifine installed?

No

### Describe the issue

Copy-Paste Gadget retains obscenely large selection range and crashes client connection

### Steps to reproduce

1. Copy something
2. Go a very long ways away in the same world (10km?)
3. Forget which click is start region vs end region and select end region instead of start
4. Get booted from server because you selected a massive region with a rendering box.
5. Log back in and hover over the copy-paste gadget in your hot bar to get booted again (along with everyone on the server)

### Expected behaviour

Selection range should be limited to something reasonable and not cause a server-wide kick-all event

### Information

- [X] I have provided as much information as possible

**Comment by Direwolf20-MC** [comment]
This should be fixed as part of a prior fix i did, but let me know if its still happening
